### PR TITLE
[DF-28] Add dependency Ant Design, Storybook

### PR DESCRIPTION
**Pull request by octobrekids**
These branches have changed a config following these
- ESlint
- Babel
Add new dependencies following these
- Antd
- Storybook

related to [DF-28](https://framekorbsine.atlassian.net/browse/DF-28)

### CODE REVIEW

**Review by octobrekids — COMMENTED** [review]
Seen

**Review by yee2542 — APPROVED** [review]
LGTM

**Review by octobrekids — COMMENTED** [review]
Seen

**Review by yee2542 — APPROVED** [review]
LGTM

**Pull request merged**
